export default {
  common: {
    commandCardStyle: "dense",
    primaryColor: "#009688",
    defaultPrimaryColor: "#009688",
    backgroundImgLight: "",
    backgroundImgDark: "",
    autofocusSearch: false,
    denseTagBar: false,
    quickFileEnable: false,
    quickFileTag: "文件",
    quickUrlEnable: false,
    quickUrlTag: "网址",
    pluNickNameEnable: false,
    pluNickNameTag: "别名",
    autoDetachFeatures: [],
    glassEffect: 0,
  },
  native: {
    crontabs: {},
    serverPort: 33442,
    serverStatus: false,
    envPath: "",
    alias: "",
  },
};
