export default {
    commandCardStyle: "normal",
    primaryColor: "#009688",
    defaultPrimaryColor: "#009688",
    backgroundImg: null,
    autofocusSearch: false,
    denseTagBar: false,
    quickFileEnable: false,
    quickFileTag: "文件",
    quickUrlEnable: false,
    quickUrlTag: "网址",
    pluNickNameEnable: false,
    pluNickNameTag: "别名",
    apiServerEnable: false,
    apiServerPort: 33442,
}