export default {
  value: "",
  // 自动布局
  automaticLayout: true,
  // 折叠策略
  foldingStrategy: "indentation",
  // 自动关闭括号
  autoClosingBrackets: true,
  // 制表符大小
  tabSize: 2,
  // 最小化
  minimap: {
    enabled: false,
  },
  // 自动格式化
  formatOnType: true,
  // 自动格式化
  formatOnPaste: true,
  // 自动缩进
  autoIndent: "full",
  // 滚动超出最后一行
  scrollBeyondLastLine: false,
  // 字体大小
  fontSize: 14,
  // 行号
  lineNumbers: "on",
  // 行号最小字符数
  lineNumbersMinChars: 3,
  // 行号
  renderLineNumbers: "on",
  // 行装饰宽度
  lineDecorationsWidth: 0,
  // 圆角
  roundedSelection: false,
  // 行高亮
  renderLineHighlight: "all",
  // 仅在聚焦时高亮行
  renderLineHighlightOnlyWhenFocus: true,
  // 隐藏光标
  hideCursorInOverviewRuler: true,
  // 隐藏概览边框
  overviewRulerBorder: false,
  // 隐藏概览线
  overviewRulerLanes: 0,
  // 滚动条
  scrollBars: {
    vertical: "visible",
    horizontal: "visible",
  },
  // 只读
  readOnly: false,
  // 光标样式
  cursorStyle: "line",
};
