var Function = ["abs", "accept", "alarm", "atan2", "bind", "binmode", "bless", "bootstrap", "break", "caller", "chdir", "chmod", "chomp", "chop", "chown", "chr", "chroot", "close", "closedir", "connect", "cos", "crypt", "dbmclose", "dbmopen", "default", "defined", "delete", "die", "do", "dump", "each", "endgrent", "endhostent", "endnetent", "endprotoent", "endpwent", "endservent", "eof", "eval", "exec", "exists", "exit", "exp", "fcntl", "fileno", "flock", "fork", "format", "formline", "getc", "getgrent", "getgrgid", "getgrnam", "gethostbyaddr", "gethostbyname", "gethostent", "getlogin", "getnetbyaddr", "getnetbyname", "getnetent", "getpeername", "getpgrp", "getppid", "getpriority", "getprotobyname", "getprotobynumber", "getprotoent", "getpwent", "getpwnam", "getpwuid", "getservbyname", "getservbyport", "getservent", "getsockname", "getsockopt", "given", "glob", "gmtime", "goto", "grep", "hex", "import", "index", "int", "ioctl", "join", "keys", "kill", "last", "lc", "lcfirst", "length", "link", "listen", "localtime", "lock", "log", "lstat", "map", "mkdir", "msgctl", "msgget", "msgrcv", "msgsnd", "new", "next", "no", "oct", "open", "opendir", "ord", "pack", "package", "pipe", "pop", "pos", "print", "printf", "prototype", "push", "rand", "read", "readdir", "readline", "readlink", "readpipe", "recv", "redo", "ref", "rename", "require", "reset", "return", "reverse", "rewinddir", "rindex", "rmdir", "say", "scalar", "seek", "seekdir", "select", "semctl", "semget", "semop", "send", "setgrent", "sethostent", "setnetent", "setpgrp", "setpriority", "setprotoent", "setpwent", "setservent", "setsockopt", "shift", "shmctl", "shmget", "shmread", "shmwrite", "shutdown", "sin", "sleep", "socket", "socketpair", "sort", "splice", "split", "sprintf", "sqrt", "srand", "stat", "state", "study", "sub", "substr", "symlink", "syscall", "sysopen", "sysread", "sysseek", "system", "syswrite", "tell", "telldir", "tie", "tied", "time", "times", "truncate", "uc", "ucfirst", "umask", "undef", "unlink", "unpack", "unshift", "untie", "use", "utime", "values", "vec", "wait", "waitpid", "wantarray", "warn", "when", "write"]
var Keyword = ["local", "my", "our"]
var Operator = ["lt", "gt", "le", "ge", "eq", "ne", "cmp", "not", "and", "or", "xor"]
var Variable = ["STDIN", "STDIN_TOP", "STDOUT", "STDOUT_TOP", "STDERR", "STDERR_TOP", "$ARG", "$_", "@ARG", "@_", "$LIST_SEPARATOR", "$\"", "$PROCESS_ID", "$PID", "$$", "$REAL_GROUP_ID", "$GID", "$(", "$EFFECTIVE_GROUP_ID", "$EGID", "$)", "$PROGRAM_NAME", "$0", "$SUBSCRIPT_SEPARATOR", "$SUBSEP", "$;", "$REAL_USER_ID", "$UID", "$<", "$EFFECTIVE_USER_ID", "$EUID", "$>", "$a", "$b", "$COMPILING", "$^C", "$DEBUGGING", "$^D", "${^ENCODING}", "$ENV", "%ENV", "$SYSTEM_FD_MAX", "$^F", "@F", "${^GLOBAL_PHASE}", "$^H", "%^H", "@INC", "%INC", "$INPLACE_EDIT", "$^I", "$^M", "$OSNAME", "$^O", "${^OPEN}", "$PERLDB", "$^P", "$SIG", "%SIG", "$BASETIME", "$^T", "${^TAINT}", "${^UNICODE}", "${^UTF8CACHE}", "${^UTF8LOCALE}", "$PERL_VERSION", "$^V", "${^WIN32_SLOPPY_STAT}", "$EXECUTABLE_NAME", "$^X", "$1", "$MATCH", "$&", "${^MATCH}", "$PREMATCH", "$`", "${^PREMATCH}", "$POSTMATCH", "$'", "${^POSTMATCH}", "$LAST_PAREN_MATCH", "$+", "$LAST_SUBMATCH_RESULT", "$^N", "@LAST_MATCH_END", "@+", "%LAST_PAREN_MATCH", "%+", "@LAST_MATCH_START", "@-", "%LAST_MATCH_START", "%-", "$LAST_REGEXP_CODE_RESULT", "$^R", "${^RE_DEBUG_FLAGS}", "${^RE_TRIE_MAXBUF}", "$ARGV", "@ARGV", "ARGV", "ARGVOUT", "$OUTPUT_FIELD_SEPARATOR", "$OFS", "$,", "$INPUT_LINE_NUMBER", "$NR", "$.", "$INPUT_RECORD_SEPARATOR", "$RS", "$/", "$OUTPUT_RECORD_SEPARATOR", "$ORS", "$\\", "$OUTPUT_AUTOFLUSH", "$|", "$ACCUMULATOR", "$^A", "$FORMAT_FORMFEED", "$^L", "$FORMAT_PAGE_NUMBER", "$%", "$FORMAT_LINES_LEFT", "$-", "$FORMAT_LINE_BREAK_CHARACTERS", "$:", "$FORMAT_LINES_PER_PAGE", "$=", "$FORMAT_TOP_NAME", "$^", "$FORMAT_NAME", "$~", "${^CHILD_ERROR_NATIVE}", "$EXTENDED_OS_ERROR", "$^E", "$EXCEPTIONS_BEING_CAUGHT", "$^S", "$WARNING", "$^W", "${^WARNING_BITS}", "$OS_ERROR", "$ERRNO", "$!", "%OS_ERROR", "%ERRNO", "%!", "$CHILD_ERROR", "$?", "$EVAL_ERROR", "$@", "$OFMT", "$#", "$*", "$ARRAY_BASE", "$[", "$OLD_PERL_VERSION", "$]"]
export default {
    Function,
    Keyword,
    Operator,
    Variable
}
