export const controlCommands = {
  label: "流程控制",
  icon: "call_split",
  commands: [
    {
      value: "condition",
      label: "条件判断",
      component: "ConditionalJudgment",
      isControlFlow: true,
      commandChain: ["if", "end"],
    },
    {
      value: "loop",
      label: "循环执行",
      component: "LoopControl",
      isControlFlow: true,
      commandChain: ["loop", "end"],
    },
    {
      value: "forEach",
      label: "遍历数组",
      component: "ForEachControl",
      isControlFlow: true,
      commandChain: ["forEach", "end"],
    },
    {
      value: "forIn",
      label: "遍历对象",
      component: "ForInControl",
      isControlFlow: true,
      commandChain: ["forIn", "end"],
    },
    {
      value: "while",
      label: "条件循环",
      component: "WhileControl",
      isControlFlow: true,
      commandChain: ["while", "end"],
    },
    {
      value: "switch",
      label: "条件分支",
      component: "SwitchControl",
      isControlFlow: true,
      commandChain: ["switch", "case", "end"],
    },
    {
      value: "tryCatch",
      label: "异常处理",
      component: "TryCatchControl",
      isControlFlow: true,
      commandChain: ["try", "catch", "end"],
    },
  ],
};
