export const statusCommands = {
  label: "获取状态",
  icon: "task",
  commands: [
    {
      value: "utools.readCurrentFolderPath",
      label: "获取当前文件管理器路径",
      desc: "获取当前文件管理器窗口路径",
      icon: "folder",
      isAsync: true,
      outputVariable: "currentFolderPath",
      saveOutput: true,
    },
    {
      value: "utools.readCurrentBrowserUrl",
      label: "获取当前浏览器地址",
      desc: "获取当前浏览器窗口URL",
      icon: "language",
      isAsync: true,
      outputVariable: "currentBrowserUrl",
      saveOutput: true,
    },
    {
      value: "quickcomposer.status.getSelectedText",
      label: "获取选中文本",
      desc: "获取选中的文本",
      icon: "text_fields",
      isAsync: true,
      outputVariable: "selectedText",
      saveOutput: true,
    },
    {
      value: "quickcomposer.status.getSelectedImage",
      label: "获取选中的图片",
      desc: "获取选中的图片",
      icon: "image",
      isAsync: true,
      outputVariable: "selectedImage",
      saveOutput: true,
    },
    {
      value: "quickcomposer.status.getSelectedFiles",
      label: "获取选中的文件",
      desc: "获取选中的文件",
      icon: "file_present",
      isAsync: true,
      outputVariable: "selectedFiles",
      saveOutput: true,
    },
  ],
};
